# Start from the latest golang base image
FROM golang:1.13 as builder

# Add Maintainer Info
LABEL maintainer="Austin Gundry <abgundry@gmail.com>"

# Set the Current Working Directory inside the container
WORKDIR /rps_financial

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependancies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source from the current directory to the Working Directory inside the container
COPY . .

# Build the Go app using makefile
# RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bin/rps_financial main.go
RUN make build-for-ubuntu-docker


######## Start a new stage from scratch #######
# Raspberry pi uses arm architecture
FROM arm64v8/alpine:3.7

RUN apk --no-cache add ca-certificates

RUN apk add --no-cache libc6-compat

WORKDIR /root/

# Copy the Pre-built binary file from the previous stage
COPY --from=builder /rps_financial/bin/rps_financial .
COPY --from=builder /rps_financial/config/prod-config.yml config.yml

# Expose port 8080 to the outside world
EXPOSE 8080

# Command to run the executable
CMD ["./rps_financial", "-config", "config.yml"]
